
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN DECL ID NUMBER TYPEstatement : DECL TYPE ID ASSIGN NUMBER'
    
_lr_action_items = {'DECL':([0,],[2,]),'$end':([1,6,],[0,-1,]),'TYPE':([2,],[3,]),'ID':([3,],[4,]),'ASSIGN':([4,],[5,]),'NUMBER':([5,],[6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> DECL TYPE ID ASSIGN NUMBER','statement',5,'p_statement','parser.py',5),
]
